package mv;

import static mv.workspace.style.MapViewerStyle.CLASS_RVMM_TOOLBAR;

/**
 * This class provides the properties that are needed to be loaded for
 * setting up the Map Viewer workspace controls including language-dependent
 * text.
 * 
 * @author Richard McKenna
 * @version 1.0
 */
public enum MapMakerPropertyType {
   // THIS IS THE MV WORKSPACE PANE
         
    // THIS IS THE MV WORKSPACE PANE
    MV_MAP_PANE, MV_MAP_VBOX, MV_MAP_VBOX_LABEL, RVMM_LEFT_MAP,
    MV_MAP_HBOX1, MV_MAP_HBOX2,
    MV_FITPLOY_BUTTON, MV_RESET_ZOOM_BUTTON,
    MV_ZOOM_IN_BUTTON, MV_ZOOM_OUT_BUTTON,
    MV_MOVE_LEFT_BUTTON, MV_MOVE_RIGHT_BUTTON,
    MV_MOVE_UP_BUTTON, MV_MOVE_DOWN_BUTTON,
    MV_LABEL, 
    RVMM_RIGHTAREA, RVMM_TABLE,
    RVMM_TABLECOL1, RVMM_TABLECOL2, RVMM_TABLECOL3,
    
    //RVMM_BOTTOM_RIGHTAREA
    RVMM_BOTTOM_RIGHTAREA1, RVMM_BOTTOM_RIGHTAREA2,
    RVMM_BOTTOM_RIGHTAREA3, RVMM_BOTTOM_RIGHTAREA4,
    
    //RVMM_BOTTOM_RIGHTAREA_VBOX1
    RVMM_BOTTOM1_1LABEL, RVMM_BOTTOM1_2LABEL, 
    RVMM_BOTTOM1_3LABEL, RVMM_BOTTOM1_4LABEL,
    RVMM_BOTTOM1_5LABEL,
    //RVMM_BOTTOM_RIGHTAREA_VBOX2
    RVMM_BOTTOM2_1LABEL, RVMM_BOTTOM2_2LABEL, 
    RVMM_BOTTOM2_3LABEL, RVMM_BOTTOM2_4LABEL,
    RVMM_BOTTOM2_5LABEL,
    //RVMM_BOTTOM1
    RVMM_BOTTOM1_SLIDER1, RVMM_BOTTOM1_SLIDER2,
    RVMM_BOTTOM1_SLIDER3, RVMM_BOTTOM2_SLIDER1,
    RVMM_BOTTOM2_SLIDER2,
    RVMM_BOTTOM1_COLORPICKER,
    //RVMM_BOTTOM2
    RVMM_BOTTOM2_CHECKBOX,
    RVMM_BOTTOM2_COLORPICKER,
    RVMM_BOTTOM2_COMBOBOX,
    
    //RVMM_TOOLBAR
    RVMM_MAIN_TOOLBAR, RVMM_TOOLBAR1, 
    RVMM_TOOLBAR2, RVMM_TOOLBAR3,
    RVMM_TOOLBAR4, RVMM_TOOLBAR5,
    RVMM_SUBTOOLBAR4, RVMM_SUBTOOLBAR5,
    
    //TOOLBAR1
    CREATEMAP_BUTTON, RVMM_TOOLBAR_BUTTON_LOAD,
    RVMM_TOOLBAR_BUTTON_SAVE, RVMM_TOOLBAR_BUTTON_EXPORT,
    RVMM_TOOLBAR_BUTTON_EXIT, RVMM_TOOLBAR_BUTTON_UNDO,
    RVMM_TOOLBAR_BUTTON_REDO,
    //TOOLBAR2
    RVMM_TOOLBAR_BUTTON_RESETVIEWPORT, RVMM_TOOLBAR_BUTTON_FITVIEWPORT,
    //TOOLBAR3
    RVMM_TOOLBAR_BUTTON_TEXT, RVMM_TOOLBAR_BUTTON_ADDIMAGE,
    RVMM_TOOLBAR_BUTTON_REMOVEIMAGE, RVMM_TOOLBAR_BUTTON_TOPLEFT,
    RVMM_TOOLBAR_BUTTON_BOTTOMLEFT, RVMM_TOOLBAR_BUTTON_CHANGE,
    RVMM_TOOLBAR_BUTTON_EXTEND,
    //TOOLBAR4
    RVMM_TOOLBAR_CHECKBOX1, RVMM_TOOLBAR_CHECKBOX2,
    RVMM_TOOLBAR_CHECKBOX1_LABEL, RVMM_TOOLBAR_CHECKBOX2_LABEL,
    //TOOLBAR5
     RVMM_TOOLBAR_COLORPICKER, RVMM_TOOLBAR_SLIDER,
     RVMM_TOOLBAR_COLORPICKER_LABEL, RVMM_TOOLBAR_SLIDER_LABEL,
   
     // Creat New Map Dialog
     CREATENEW_DIALOG_HEADER_LABEL, CREATENEW_DIALOG_REGIONAME_LABEL,
     CREATENEW_DIALOG_PARENTS_LABEL, CREATENEW_DIALOG_DATACHOICE_LABEL,
     CREATENEW_DIALOG_PARENTS_BUTTON, CREATENEW_DIALOG_DATACHOICE_BUTTON,
     CREATENEW_DIALOG_HEADER_LABEL_TEXT, CREATENEW_DIALOG_OKBUTTON,
     
     // Change Diemension Dialog
     MAP_DIMENSIONS_DIALOG_HEADER_LABEL, MAP_DIMENSIONS_DIALOG_HEIGHT_LABEL,
     MAP_DIMENSIONS_DIALOG_WIDTH_BUTTON, MAP_DIMENSIONS_DIALOG_OKBUTTON,
     MAP_DIMENSIONS_DIALOG_HEADER_LABEL_TEXT,
     
     // Map Maker View / Edit Subregion Dialog
     EDITSUB_DIALOG_HEADER_LABEL, EDITSUB_DIALOG_PREV_BUTTON,
     EDITSUB_DIALOG_NEXT_BUTTON, EDITSUB_DIALOG_SUBREIONNAME_LABEL,
     EDITSUB_DIALOG_CAPTIAL_LABEL, EDITSUB_DIALOG_LEADER_LABEL,
     EDITSUB_DIALOG_FLAG_LABEL, EDITSUB_DIALOG_HEADER_LABEL_TEXT,
     EDITSUB_DIALOG_OKBUTTON,EDITSUB_DIALOG_FALG_IMAGE,
     
//    MV_MAP_LEFTCOL, MV_MAP_RIGHTCOL,

    // FOOLPROOF SETTINGS
    MV_FOOLPROOF_SETTINGS,
    change_polygon,change_polygon_title,
    Move_Polygon, Move_polygon_title,
    // THIS IS THE EXPORT TEMPLATE FILE NAME
    MV_EXPORT_TEMPLATE_FILE_NAME
}