package mv;

/**
 * This class provides the properties that are needed to be loaded for
 * setting up the Map Viewer workspace controls including language-dependent
 * text.
 * 
 * @author Richard McKenna
 * @version 1.0
 */
public enum MapMakerPropertyType {
   // THIS IS THE MV WORKSPACE PANE
         
    // THIS IS THE MV WORKSPACE PANE
    MV_MAP_PANE, MV_MAP_VBOX, MV_MAP_VBOX_LABEL,
    MV_MAP_HBOX1, MV_MAP_HBOX2,
    MV_FITPLOY_BUTTON, MV_RESET_ZOOM_BUTTON,
    MV_ZOOM_IN_BUTTON, MV_ZOOM_OUT_BUTTON,
    MV_MOVE_LEFT_BUTTON, MV_MOVE_RIGHT_BUTTON,
    MV_MOVE_UP_BUTTON, MV_MOVE_DOWN_BUTTON,
    MV_LABEL, 
    RVMM_RIGHTAREA, RVMM_TABLE,
    RVMM_TABLECOL1, RVMM_TABLECOL2, RVMM_TABLECOL3,
    
    //RVMM_BOTTOM_RIGHTAREA
    RVMM_BOTTOM_RIGHTAREA1, RVMM_BOTTOM_RIGHTAREA2,
    RVMM_BOTTOM_RIGHTAREA3, RVMM_BOTTOM_RIGHTAREA4,
    
    //RVMM_BOTTOM_RIGHTAREA_VBOX1
    RVMM_BOTTOM1_1LABEL, RVMM_BOTTOM1_2LABEL, 
    RVMM_BOTTOM1_3LABEL, RVMM_BOTTOM1_4LABEL,
    RVMM_BOTTOM1_5LABEL,
    //RVMM_BOTTOM_RIGHTAREA_VBOX2
    RVMM_BOTTOM2_1LABEL, RVMM_BOTTOM2_2LABEL, 
    RVMM_BOTTOM2_3LABEL, RVMM_BOTTOM2_4LABEL,
    RVMM_BOTTOM2_5LABEL,
    //RVMM_BOTTOM1
    RVMM_BOTTOM1_SLIDER1, RVMM_BOTTOM1_SLIDER2,
    RVMM_BOTTOM1_SLIDER3, RVMM_BOTTOM2_SLIDER1,
    RVMM_BOTTOM2_SLIDER2,
    RVMM_BOTTOM1_COLORPICKER,
    //RVMM_BOTTOM2
    RVMM_BOTTOM2_CHECKBOX,
    RVMM_BOTTOM2_COLORPICKER,
    RVMM_BOTTOM2_COMBOBOX,
    
//    MV_MAP_LEFTCOL, MV_MAP_RIGHTCOL,

    // FOOLPROOF SETTINGS
    MV_FOOLPROOF_SETTINGS,
        
    // THIS IS THE EXPORT TEMPLATE FILE NAME
    MV_EXPORT_TEMPLATE_FILE_NAME
}